### ISSUE TITLE
issues with current build

### ISSUE THREAD

**Issue by eefahy** [sul-dlss-labs/taco#230]
deployed my `deploy` branch to the dev environment (via a tag) and ran the following curl command on with the following result:
```
▶ curl -X POST -H "Content-Type: application/json" -d@examples/request.json http://taco-dev.sul.stanford.edu/v1/resource
{"message":"UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: 0OFKEB1TV40M11SQK51O14J95NVV4KQNSO5AEMVJF66Q9ASUAAJG","stack":"goroutine 521 [running]:
runtime/debug.Stack(0xc4201f2fc0, 0x1f4, 0xc420455c20)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/sul-dlss-labs/taco/middleware.(*Recovery).ServeHTTP.func1(0xbff8e0, 0xc4201f2fc0, 0xc4204e7940)
	/go/src/github.com/sul-dlss-labs/taco/middleware/recovery.go:38 +0x91
panic(0xae8940, 0xc420455c20)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/sul-dlss-labs/taco/handlers.(*depositResourceEntry).Handle(0xc4203170e0, 0xc4203ed600, 0xc4208b5280, 0xbf9300, 0xc4205ee920)
	/go/src/github.com/sul-dlss-labs/taco/handlers/deposit_resource.go:32 +0x1e5
github.com/sul-dlss-labs/taco/generated/restapi/operations.(*DepositResource).ServeHTTP(0xc42040fb40, 0xbfece0, 0xc4204e6500, 0xc4203ed600)
	/go/src/github.com/sul-dlss-labs/taco/generated/restapi/operations/deposit_resource.go:56 +0x162
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0xbfece0, 0xc4204e6500, 0xc4203ed600)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x6e
net/http.HandlerFunc.ServeHTTP(0xc42072fe50, 0xbfece0, 0xc4204e6500, 0xc4203ed600)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0xbfece0, 0xc4204e6500, 0xc4203ed500)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/router.go:74 +0x357
net/http.HandlerFunc.ServeHTTP(0xc4204e73c0, 0xbfece0, 0xc4204e6500, 0xc4203ed500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0xbfece0, 0xc4204e6500, 0xc4203ed500)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x94
net/http.HandlerFunc.ServeHTTP(0xc4208a6e80, 0xbfece0, 0xc4204e6500, 0xc4203ed500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0xbfece0, 0xc4204e6500, 0xc4203ed500)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x73
net/http.HandlerFunc.ServeHTTP(0xc4208a6ec0, 0xbfece0, 0xc4204e6500, 0xc4203ed500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/sul-dlss-labs/taco/middleware.(*RequestLogger).ServeHTTP(0xc420782390, 0xbff8e0, 0xc4201f2fc0, 0xc4203ed500)
	/go/src/github.com/sul-dlss-labs/taco/middleware/logger.go:32 +0xb9
github.com/sul-dlss-labs/taco/middleware.(*Recovery).ServeHTTP(0xc4204e7940, 0xbff8e0, 0xc4201f2fc0, 0xc4203ed500)
	/go/src/github.com/sul-dlss-labs/taco/middleware/recovery.go:49 +0x90
github.com/sul-dlss-labs/taco/vendor/github.com/honeybadger-io/honeybadger-go.(*Client).Handler.func1(0xbff8e0, 0xc4201f2fc0, 0xc4203ed500)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/honeybadger-io/honeybadger-go/client.go:99 +0x94
net/http.HandlerFunc.ServeHTTP(0xc4204e7960, 0xbff8e0, 0xc4201f2fc0, 0xc4203ed500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc4208276c0, 0xbff8e0, 0xc4201f2fc0, 0xc4203ed500)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42028cb40, 0xbfff20, 0xc4208a6640)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
","type":"error"}% 
```

- why are we returning the stack trace as a message to the requestor?
- whats the `security token` it's looking for? honeybadger maybe?
  - I have not set the honeybadger api key on the container yet, but I thought we made that optional?

**Comment by jcoyne** [comment]
It looks like this might be related to Kinesis:
https://github.com/awslabs/amazon-kinesis-scaling-utils/issues/5

**Comment by jcoyne** [comment]
Or more generally, the AWS credentials: https://forums.aws.amazon.com/thread.jspa?threadID=86570
